<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

In [4]:
import numpy as np

# Exercise 1

Subsetting: To select

Indexing: Selecting 1 element

Slicing: Selecting a range of elements

Masking: Covering and revealing certain elements based on stated criteria

# Exercise 2

In [3]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [17]:
first_column = np_array_2d[:, 0]

In [18]:
print(first_column)

['1' '3' '2' '4' '5' '7' '6' '8' '10' '9']


In [19]:
first_column = np_array_2d[:, 0].astype(int)
print(first_column)

[ 1  3  2  4  5  7  6  8 10  9]


In [25]:
remainder = first_column % 2
print(remainder)

[1 1 0 0 1 1 0 0 0 1]


In [27]:
odd = remainder == 1
print (odd)

[ True  True False False  True  True False False False  True]


In [29]:
odd_letters = np_array_2d[odd == True, 1]

In [30]:
print(odd_letters)

['A' 'C' 'E' 'G' 'I']


# Exercise 3

In [14]:
py_list_2d = [
[66, 50, 57, -1, -1],
[92, -1, 88, -1, -1],
[75, -1, -1, 76, -1],
[-1, 51, 87, -1, -1],
[71, -1, 67, -1, 69]
]

In [15]:
np_array = np.array(py_list_2d)

In [16]:
print(np_array)

[[66 50 57 -1 -1]
 [92 -1 88 -1 -1]
 [75 -1 -1 76 -1]
 [-1 51 87 -1 -1]
 [71 -1 67 -1 69]]


In [17]:
np_array[np_array < 50] = '-1'

In [24]:
np_array[np_array > 50] = '+1'

In [19]:
np_array[np_array == 50] = '0'

In [22]:
print(np_array)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
