<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

In [1]:
import numpy as np

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

## 1.2 Accessing data from a list (or array)

In [2]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [3]:
py_real_names[0]

'Natasha Romanoff'

In [6]:
py_super_names[1]

'Iron Man'

In [9]:
py_super_names[2]

'Doctor Strange'

In [10]:
py_super_names[-1]

'Doctor Strange'

## 1.3 Accessing data from a dictionary

In [11]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}                  

In [12]:
superhero_info["Natasha Romanoff"]

'Black Widow'

In [13]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [14]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## 1.4 Higher dimensional lists

In [16]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']] #have 2 lists

# 2 Lists vs. Arrays

In [17]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [19]:
len(py_list_2d)

10

In [24]:
len(np_array_2d)
np_array_2d.shape #no bracket cus it is not a function but a property

(10, 2)

## 2.1 Size

## 2.2 Arrays are fussy about type

In [25]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

In [27]:
py_list

[1, 1.5, 'A']

In [30]:
np_array #NumPy arrays tolerate only a single type.

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [31]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [32]:
np_array + 10

array([11, 12, 13, 14, 15])

## 2.4 Adding another list

In [33]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [34]:
py_list_1 + py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [35]:
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [36]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [37]:
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [38]:
np_array*2

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [39]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [40]:
np_array**2

array([ 1,  4,  9, 16, 25])

## 2.7 Asking questions

In [41]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [42]:
py_list == 3 #question asked is if the entire list is only have 3

False

In [46]:
py_list == [1, 2, 3, 4, 5]

True

In [43]:
np_array == 3

array([False, False,  True, False, False])

In [44]:
np_array > 3

array([False, False, False,  True,  True])

## 2.8 Mathematics

## Footnotes